#!/usr/bin/env bash
# =============================================================================
# Start the local preview stack: Postgres + backend + frontend.
# =============================================================================
# Idempotent by design. Every service is checked before it is started, so
# running this twice reuses what is up rather than starting a second copy — the
# common failure mode being two Vite instances fighting over port 5173, or a
# second backend silently failing to bind :3000.
#
# Run with `status` to report what is up without changing anything.
# =============================================================================
set -uo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/preview-lib.sh"

MODE="${1:-start}"
cd "$REPO_ROOT" || exit 1

# ---------------------------------------------------------------------------
# Status report — also the first half of a start, so a start always says what
# it found before it says what it did.
# ---------------------------------------------------------------------------
step "Checking what is already running"

PG_UP=false; BE_UP=false; FE_UP=false
pg_running && PG_UP=true
http_ok "http://localhost:$BACKEND_PORT/health" && BE_UP=true
http_ok "http://localhost:$FRONTEND_PORT/" && FE_UP=true

$PG_UP && ok "Postgres  :$PG_PORT"       || say "   --   Postgres  :$PG_PORT  not running"
$BE_UP && ok "backend   :$BACKEND_PORT"  || say "   --   backend   :$BACKEND_PORT  not running"
$FE_UP && ok "frontend  :$FRONTEND_PORT" || say "   --   frontend  :$FRONTEND_PORT  not running"

if [ "$MODE" = "status" ]; then
  if $FE_UP; then say ""; say "Preview: http://localhost:$FRONTEND_PORT/dashboard"; fi
  exit 0
fi

# ---------------------------------------------------------------------------
# Preconditions
# ---------------------------------------------------------------------------
step "Preconditions"

[ -f "$REPO_ROOT/package.json" ] || { warn "not in the hotelgame repo"; exit 1; }
[ -x "$PG_BIN/pg_ctl" ] || { warn "postgresql@14 not found at $PG_BIN (brew install postgresql@14)"; exit 1; }
[ -d "$REPO_ROOT/node_modules" ] || { warn "run 'npm install' first"; exit 1; }
[ -d "$REPO_ROOT/server/node_modules" ] || { warn "run 'npm install' in server/ first"; exit 1; }
mkdir -p "$LOG_DIR"

# The preview env file is generated, gitignored, and local-only. Created once
# with a stable JWT secret so an anonymous browser session survives a restart.
if [ ! -f "$PREVIEW_ENV" ]; then
  SECRET=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
  cat > "$PREVIEW_ENV" <<EOF
# Local preview only — generated by the /local-preview skill. Gitignored.
# Every value points at this machine; none of it can reach production.
VITE_WS_URL=http://localhost:$BACKEND_PORT
DATABASE_URL=postgres://postgres@127.0.0.1:$PG_PORT/$PG_DB
JWT_SECRET=$SECRET
ALLOWED_ORIGINS=http://localhost:$FRONTEND_PORT,http://localhost:4173
PORT=$BACKEND_PORT
EOF
  ok "created .env.preview.local"
else
  ok ".env.preview.local present"
fi

set -a; source "$PREVIEW_ENV"; set +a
assert_local_only "$DATABASE_URL" || exit 1
ok "DATABASE_URL is loopback — production is unreachable from this stack"

# ---------------------------------------------------------------------------
# 1. Postgres
# ---------------------------------------------------------------------------
step "1/3  Postgres"

if $PG_UP; then
  skip "Postgres :$PG_PORT"
else
  if port_busy "$PG_PORT"; then
    warn "port $PG_PORT is taken by: $(cmd_of_pid "$(pid_on_port "$PG_PORT")")"
    warn "not ours — stop it or change PG_PORT in preview-lib.sh"; exit 1
  fi
  if [ ! -d "$PG_DATA/base" ]; then
    mkdir -p "$(dirname "$PG_DATA")"
    "$PG_BIN/initdb" -D "$PG_DATA" -U postgres --auth=trust -E UTF8 >/dev/null 2>&1 \
      || { warn "initdb failed"; exit 1; }
    ok "created cluster at $PG_DATA"
  fi
  # Loopback only: this cluster is not reachable from the network at all.
  "$PG_BIN/pg_ctl" -D "$PG_DATA" \
    -o "-p $PG_PORT -c listen_addresses=127.0.0.1 -k /tmp" \
    -l "$PG_LOG" start >/dev/null 2>&1
  sleep 2
  pg_running || { warn "Postgres failed to start — see $PG_LOG"; exit 1; }
  ok "started Postgres :$PG_PORT"
fi

export PGHOST=127.0.0.1 PGPORT=$PG_PORT PGUSER=postgres
psql -tc "SELECT 1 FROM pg_database WHERE datname='$PG_DB'" 2>/dev/null | grep -q 1 \
  || { psql -q -c "CREATE DATABASE $PG_DB;" >/dev/null 2>&1 && ok "created database $PG_DB"; }

# db/schema.sql is the complete, idempotent state — it already folds in the
# Epic 14/15/16 migrations, so a local DB never needs them applied separately.
# Re-applied every start so a schema change lands without anyone remembering to.
psql -q -d "$PG_DB" -f "$REPO_ROOT/db/schema.sql" >/dev/null 2>&1 \
  && ok "schema applied (idempotent)" \
  || { warn "schema failed to apply"; exit 1; }

# ---------------------------------------------------------------------------
# 2. Backend
# ---------------------------------------------------------------------------
step "2/3  Backend"

if $BE_UP; then
  skip "backend :$BACKEND_PORT"
else
  if port_busy "$BACKEND_PORT"; then
    warn "port $BACKEND_PORT taken but /health does not answer: $(cmd_of_pid "$(pid_on_port "$BACKEND_PORT")")"
    exit 1
  fi

  # Rebuild when the compiled entrypoint is missing or older than any source.
  NEWEST_SRC=$(find "$REPO_ROOT/server" "$REPO_ROOT/src/types" -name '*.ts' -newer "$REPO_ROOT/dist/server/server.js" 2>/dev/null | head -1)
  if [ ! -f "$REPO_ROOT/dist/server/server.js" ] || [ -n "$NEWEST_SRC" ]; then
    say "   building backend..."
    (cd "$REPO_ROOT/server" && npm run build >/dev/null 2>&1) \
      || { warn "backend build failed — run 'cd server && npm run build' to see why"; exit 1; }
    ok "built dist/server/"
  else
    ok "backend build up to date"
  fi

  # Two things the Docker image gets for free, because there server/package.json
  # IS /app/package.json and /app/node_modules is installed from it:
  #   * dist/*.js must resolve as CommonJS, but the repo root declares
  #     "type": "module", so Node would read them as ESM and die on `exports`.
  #   * dist/server/*.js resolves node_modules upward, and the backend's deps
  #     live in server/node_modules, which is not on that path.
  # Both are fixed inside dist/, which is gitignored build output.
  printf '{ "type": "commonjs" }\n' > "$REPO_ROOT/dist/package.json"
  ln -sfn ../server/node_modules "$REPO_ROOT/dist/node_modules"

  # cwd is the repo root, as in the container: the static handler serves ./dist
  # and results.ts reads the app version from ./package.json.
  cd "$REPO_ROOT" || exit 1
  nohup node dist/server/server.js </dev/null >"$BACKEND_LOG" 2>&1 &
  disown $! 2>/dev/null
  for _ in 1 2 3 4 5 6 7 8 9 10; do
    http_ok "http://localhost:$BACKEND_PORT/health" && break
    sleep 1
  done
  http_ok "http://localhost:$BACKEND_PORT/health" \
    && ok "started backend :$BACKEND_PORT" \
    || { warn "backend did not come up — see $BACKEND_LOG"; tail -5 "$BACKEND_LOG"; exit 1; }
fi

# ---------------------------------------------------------------------------
# 3. Frontend
# ---------------------------------------------------------------------------
step "3/3  Frontend"

if $FE_UP; then
  # A Vite already on 5173 may be a plain `npm run dev`, which reads .env and
  # would open a realtime connection to the PRODUCTION relay. Worth saying.
  if ps -ax -o command= | grep -q "[v]ite.*--mode preview"; then
    skip "frontend :$FRONTEND_PORT (preview mode)"
  else
    warn "something is on :$FRONTEND_PORT but was not started with --mode preview."
    warn "It will use .env's VITE_WS_URL, which points at production's relay."
    warn "Run /local-preview-end first, then start again."
  fi
else
  # --mode preview is what makes .env.preview.local win over .env. Without it
  # the browser connects its websocket to wss://server.jonashapp.com.
  #
  # node_modules/.bin/vite directly, never `npx`: npx leaves an `npm exec`
  # supervisor process alive as a child of the launching shell, so this script
  # would start everything correctly and then hang forever instead of exiting.
  cd "$REPO_ROOT" || exit 1
  nohup node_modules/.bin/vite --host --mode preview </dev/null >"$FRONTEND_LOG" 2>&1 &
  disown $! 2>/dev/null
  for _ in 1 2 3 4 5 6 7 8 9 10; do
    http_ok "http://localhost:$FRONTEND_PORT/" && break
    sleep 1
  done
  http_ok "http://localhost:$FRONTEND_PORT/" \
    && ok "started frontend :$FRONTEND_PORT (mode=preview)" \
    || { warn "frontend did not come up — see $FRONTEND_LOG"; tail -5 "$FRONTEND_LOG"; exit 1; }
fi

# ---------------------------------------------------------------------------
step "Ready"
WS=$(grep -E '^VITE_WS_URL=' "$PREVIEW_ENV" | cut -d= -f2-)
say "   app        http://localhost:$FRONTEND_PORT"
say "   dashboard  http://localhost:$FRONTEND_PORT/dashboard"
say "   realtime   $WS"
say "   database   postgres://postgres@127.0.0.1:$PG_PORT/$PG_DB"
say ""
say "   Play: Online Multiplayer -> Create Room -> set rules -> Add Bot x2 -> Ready."
say "   Stop with /local-preview-end. Logs in $LOG_DIR."
